### ISSUE TITLE
Replace is broken

### ISSUE THREAD

**Issue by vladubogdan** [faceleg/ACEView#11]
When you enter find and replace. All is good the first time. After you click the first time on "Replace" button, then the selection in ace is offset. Replacing after that will just replace wrong text. 

I'm investigating for a fix, but if you have a faster idea of what might be wrong please let me know.

**Comment by faceleg** [comment]
Fixed

**Comment by mmattozzi** [comment]
Was there a fix for this? I see in commit 7a2fef661f12a7455e292311ed7b79da1df693ff that it looks like the Javascript find/replace was disabled... does that mean the Cocoa Interface Builder find/replace can be wired up somehow (sorry, not exactly sure the proper terminology on what you call the native OS X edit menu)? Or is find/replace just turned off for now?

**Comment by faceleg** [comment]
The goal of this project is to provide a native interface - search and replace should be working via the native bridge now.

**Comment by mmattozzi** [comment]
If I add showFindInterface and showReplaceInterface to ACEView.h and wire the Find menu item up directly so that showFindInterface gets called in my code, then everything works ok. However, is the intent that the "normal" wiring of the Find menu items to 'First Responder' should just work by virtue of ACEView implementing the NSTextFinderClient protocol? That doesn't seem to do anything for me... it doesn't seem to work in ACEViewExample either. Unless something is totally going haywire with my Xcode build. 

Thanks for the clarity on this!

**Comment by faceleg** [comment]
Hmmm. I thought it shoud "just work". Does it work out of the box with the example app?

**Comment by mmattozzi** [comment]
Did not work for me with the example app. Running XCode 6.1.1 on OS X 10.9.4.

**Comment by faceleg** [comment]
Hmm... I'll check my private project that uses it

**Comment by faceleg** [comment]
I haven't done anything special in my controller to get COMMAND+F working natively
